version: "3.8"

services:
  webapp1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp1
    restart: unless-stopped

    environment:
      - DATABASE_URL=
      - REDIS_URL=
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret
      - S3_ENDPOINT=
      - S3_BUCKET_REGION=
      - S3_BUCKET_NAME=
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
      - S3_PUBLIC_URL=
      - USE_AVIRAL=true
      - GOOGLE_APPLICATION_CREDENTIALS=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - ENCRYPTION_KEY=foEj2dBZb6TrUsD0Z42LbAnK1JfIuc5Q1iOTMj6yEKw=
    env_file:
      - .env
    networks:
      - internal

  webapp2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp2
    restart: unless-stopped

    environment:
      - DATABASE_URL=
      - REDIS_URL=
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret
      - S3_ENDPOINT=
      - S3_BUCKET_REGION=
      - S3_BUCKET_NAME=
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
      - S3_PUBLIC_URL=
      - USE_AVIRAL=true
      - GOOGLE_APPLICATION_CREDENTIALS=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - ENCRYPTION_KEY=foEj2dBZb6TrUsD0Z42LbAnK1JfIuc5Q1iOTMj6yEKw=
    env_file:
      - .env
    networks:
      - internal

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_reverse_proxy
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - webapp1
      - webapp2
    networks:
      - internal

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: utkarsh
      MYSQL_DATABASE: utkarsh
      MYSQL_USER: utkarsh
      MYSQL_PASSWORD: utkarsh
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - internal

  cache:
    image: redis:7
    container_name: redis_cache
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:

volumes:
  mysql:
