name: Build Test the code

on:
  push:
    branches:
      - "*"
      - "!prod"

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      SKIP_ENV_VALIDATION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build web-app
        run: npm run build
